using System.Text.Json.Serialization;

namespace IntegratedS3.Provider.Disk.Internal;

[JsonSerializable(typeof(DiskObjectMetadata))]
[JsonSerializable(typeof(DiskBucketMetadata))]
[JsonSerializable(typeof(DiskBucketCorsConfiguration))]
[JsonSerializable(typeof(DiskBucketCorsRule))]
[JsonSerializable(typeof(DiskMultipartUploadState))]
[JsonSerializable(typeof(DiskBucketTaggingConfiguration))]
[JsonSerializable(typeof(DiskBucketLoggingConfiguration))]
[JsonSerializable(typeof(DiskBucketWebsiteConfiguration))]
[JsonSerializable(typeof(DiskBucketWebsiteRedirectAllRequestsTo))]
[JsonSerializable(typeof(DiskBucketWebsiteRoutingRule))]
[JsonSerializable(typeof(DiskBucketWebsiteRoutingRuleCondition))]
[JsonSerializable(typeof(DiskBucketWebsiteRoutingRuleRedirect))]
[JsonSerializable(typeof(DiskBucketRequestPaymentConfiguration))]
[JsonSerializable(typeof(DiskBucketAccelerateConfiguration))]
[JsonSerializable(typeof(DiskBucketLifecycleConfiguration))]
[JsonSerializable(typeof(DiskBucketLifecycleRule))]
[JsonSerializable(typeof(DiskBucketLifecycleTransition))]
[JsonSerializable(typeof(DiskBucketLifecycleNoncurrentVersionTransition))]
[JsonSerializable(typeof(DiskBucketReplicationConfiguration))]
[JsonSerializable(typeof(DiskBucketReplicationRule))]
[JsonSerializable(typeof(DiskBucketReplicationDestination))]
[JsonSerializable(typeof(DiskBucketNotificationConfiguration))]
[JsonSerializable(typeof(DiskBucketNotificationTopicConfiguration))]
[JsonSerializable(typeof(DiskBucketNotificationQueueConfiguration))]
[JsonSerializable(typeof(DiskBucketNotificationLambdaConfiguration))]
[JsonSerializable(typeof(DiskBucketNotificationFilter))]
[JsonSerializable(typeof(DiskBucketNotificationFilterRule))]
[JsonSerializable(typeof(DiskBucketObjectLockConfiguration))]
[JsonSerializable(typeof(DiskObjectLockDefaultRetention))]
[JsonSerializable(typeof(DiskBucketAnalyticsConfiguration))]
[JsonSerializable(typeof(DiskBucketAnalyticsStorageClassAnalysis))]
[JsonSerializable(typeof(DiskBucketAnalyticsDataExport))]
[JsonSerializable(typeof(DiskBucketAnalyticsS3BucketDestination))]
[JsonSerializable(typeof(DiskBucketMetricsConfiguration))]
[JsonSerializable(typeof(DiskBucketMetricsFilter))]
[JsonSerializable(typeof(DiskBucketInventoryConfiguration))]
[JsonSerializable(typeof(DiskBucketInventoryDestination))]
[JsonSerializable(typeof(DiskBucketInventoryS3BucketDestination))]
[JsonSerializable(typeof(DiskBucketInventorySchedule))]
[JsonSerializable(typeof(DiskBucketInventoryFilter))]
[JsonSerializable(typeof(DiskBucketIntelligentTieringConfiguration))]
[JsonSerializable(typeof(DiskBucketIntelligentTieringFilter))]
[JsonSerializable(typeof(DiskBucketIntelligentTiering))]
[JsonSerializable(typeof(Dictionary<string, DiskBucketAnalyticsConfiguration>))]
[JsonSerializable(typeof(Dictionary<string, DiskBucketMetricsConfiguration>))]
[JsonSerializable(typeof(Dictionary<string, DiskBucketInventoryConfiguration>))]
[JsonSerializable(typeof(Dictionary<string, DiskBucketIntelligentTieringConfiguration>))]
internal partial class DiskStorageJsonSerializerContext : JsonSerializerContext
{
}
