namespace IntegratedS3.Core.Models;

public enum StorageOperationType
{
    ListBuckets,
    CreateBucket,
    HeadBucket,
    DeleteBucket,
    GetBucketAcl,
    PutBucketAcl,
    GetBucketPolicy,
    PutBucketPolicy,
    DeleteBucketPolicy,
    GetBucketVersioning,
    PutBucketVersioning,
    GetBucketCors,
    PutBucketCors,
    DeleteBucketCors,
    ListObjects,
    ListObjectVersions,
    ListMultipartUploads,
    GetObject,
    HeadObject,
    GetObjectAcl,
    PutObjectAcl,
    GetObjectTags,
    CopyObject,
    PutObject,
    DeleteObject,
    PresignPutObject,
    PresignGetObject,
    PutObjectTags,
    DeleteObjectTags,
    InitiateMultipartUpload,
    UploadMultipartPart,
    CompleteMultipartUpload,
    AbortMultipartUpload
}
